name: Portfolio CI tests workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: my-app

      - name: Run tests
        run: npm test a
        working-directory: my-app

      - name: Build project
        if: ${{ success() }}
        run: npm run build
        working-directory: my-app

      - name: Deploy to Vercel
        if: ${{ success() }}
        id: deployment
        uses: amondnet/vercel-action@v20
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: --prod
